#!/bin/sh
echo "🔄 Waiting for PostgreSQL to be ready..."

# Wait until PostgreSQL is available
until nc -z -v -w30 "$DB_HOST" "$DB_PORT"; do
  echo "⏳ Waiting for database connection at $DB_HOST:$DB_PORT..."
  sleep 5
done

echo "✅ Database is up, starting Java application..."

# Run the shaded JAR from Maven (generated by maven-shade-plugin)
exec java -jar app.jar
