# PostgreSQL
db.host=localhost
db.port=5432
db.name=postgres
db.user=postgres
db.password=#1234

postgres.host=localhost
postgres.port=5432

app.db.name=app_db
app.db.user=app_user
app.db.password=#nem_reader123$

flyway.mix=true